"""Build ab_testing_methodology_narrative_v3.md from v2 by replacing Section 8."""

from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
V2 = ROOT / "ab_testing_methodology_narrative_v2.md"
V3 = ROOT / "ab_testing_methodology_narrative_v3.md"

src = V2.read_text()

section8_start = "## 8. Worked example: a battle-pass offer UI test"
section9_start = "## 9. Tensions with current practice and directions for improvement"

i = src.index(section8_start)
j = src.index(section9_start)

NEW_SECTION_8 = r"""## 8. Worked example: recovering a known uplift from real IAP data

To stress-test the methodology on real game economics rather than invented
numbers, we use a one-week sample of in-app-purchase (IAP) revenue from
the live operations of one of the studio's mobile titles. The sample
covers the window **2026-05-04 to 2026-05-10** and contains
**195,524 distinct user accounts** that hit the server in that window.
User identifiers are pseudonymized; the `IAP_REVENUE` column is the
genuine total USD spend per user over the seven days. The dataset is
checked into this repository at
`data/iap_revenue_2026-05-04_to_2026-05-10.csv` and the analysis script
that produced every number in this section is at
`scripts/section8_analysis.py`.

The structure of this section mirrors the methodology chapters:

1. **Section 8.1** describes the dataset with two visualizations and a
   table of summary statistics.
2. **Section 8.2** lays out the simulation design used to convert this
   single sample into a controlled A/B experiment in which the true
   uplift is known.
3. **Section 8.3** walks one randomly chosen iteration of the simulation
   number-by-number, tying every quantity back to equations (1)-(9),
   (13)-(16), and (17).
4. **Section 8.4** aggregates results across $R = 100$ such iterations
   and reports how well the methodology recovers the injected uplift.
5. **Section 8.5** discusses what the simulation reveals about the
   pipeline's calibration and power for a KPI of this shape.

A note on Section 5 (CUPED). The dataset supplied for this section
contains only the in-period outcome $Y_i$ (one week of IAP revenue per
user); no pre-experiment covariate vector $\mathbf{x}_i$ is available.
The worked example therefore operates on the **raw** outcome throughout,
and the CUPED variance-reduction step is *not* exercised here. The other
steps of the pipeline (3.2, 4, 6, 7.1) all apply unchanged.

### 8.1 The dataset

**Headline shape.** Among the 195,524 users in the window, **183,666
(93.94%) spent nothing** in the seven-day period and **11,858 (6.06%)
made at least one purchase**. The unconditional weekly per-user revenue
has mean $\bar Y^{\text{all}} = \$1.2936$ and sample standard deviation
$s^{\text{all}} = \$11.4303$, a coefficient of variation
$s^{\text{all}} / \bar Y^{\text{all}} \approx 8.8$ that is characteristic
of mobile free-to-play economics: most users are free riders and a small
tail of paying users — including a smaller tail of spenders well above
$\$100$ in a single week — drives the mean.

**Summary statistics.** The table below collects the key descriptors.
"All users" is the population we sample from in Section 8.2; "Paying
users" conditions on $Y_i > 0$ and is shown to give a sense of the
within-payer distribution.

| Quantity | All users ($n = 195{,}524$) | Paying users ($n = 11{,}858$) |
|---|---|---|
| Mean weekly revenue | $\$1.2936$ | $\$21.3295$ |
| Median | $\$0.00$ | $\$9.99$ |
| Sample SD | $\$11.4303$ | $\$41.5578$ |
| Maximum | $\$1{,}402.45$ | $\$1{,}402.45$ |
| 95th percentile | $\$3.88$ | $\$74.91$ |
| 99th percentile | $\$32.25$ | $\$176.35$ |
| 99.9th percentile | $\$128.88$ | — |
| Share of all users | $100\%$ | $6.06\%$ |
| Share of total revenue | $100\%$ | $100\%$ |

Total weekly revenue across the sample is $\$252{,}924.84$. The
median user contributes $\$0$, so the entire mean is generated by the
top $\sim 6\%$ of users.

**Figure 1** shows the composition of the sample (left panel) and the
distribution among paying users on a log scale (right panel).

![Composition of the sample and distribution among paying users.](figures/fig1_distribution.png){ width=100% }

**Figure 2** quantifies how concentrated revenue is. The top **1%** of
users (1,955 of them) account for **59.8%** of weekly revenue; the top
**0.1%** (195 users) account for **19.2%**; the top **5%** account for
**97.9%**. This kind of Pareto-like concentration is precisely why
variance reduction matters in this domain — and why, with no CUPED
adjustment available in this dataset, we should expect comparatively
large standard errors on $\hat\rho_t$ relative to a covariate-adjusted
analysis.

![Lorenz curve of weekly IAP revenue.](figures/fig2_lorenz.png){ width=80% }

### 8.2 Simulation design

Because we observe only a single realized week of data, we do not have
two parallel experimental arms in the wild. Instead we use the sample as
a population from which to construct repeated synthetic A/B experiments
where the **ground-truth relative uplift is known by construction**.
This lets us answer two complementary questions:

1. Is the methodology *calibrated*? That is, when we set
   $\rho_t = 0.05$, does $\hat\rho_t$ on average land near 5%, and do
   the reported 95% credible intervals cover the truth roughly 95% of
   the time?
2. Is the methodology *powered* for a one-week test of this size?
   That is, how often does the chance-to-beat-control summary
   $P(\rho_t > 0 \,|\, \text{data})$ from Section 6.3 cross the
   $0.95$ decision threshold?

The protocol for one iteration is:

1. Randomly permute the $N = 195{,}524$ user-level revenue values and
   split the sequence in half, producing two **disjoint** subsamples
   $\mathcal{I}_C$ and $\mathcal{I}_T$ of size $n_C = n_T = 97{,}762$
   (one user is dropped to make the halves equal). This emulates a true
   $50{:}50$ randomized assignment.
2. Leave the control values $\{Y_i : i \in \mathcal{I}_C\}$ untouched.
   Multiply each treatment value by $1 + \rho^{\star}$ with the injected
   relative uplift $\rho^{\star} = 0.05$, giving
   $Y_i^{T} = (1 + \rho^{\star}) Y_i$ for $i \in \mathcal{I}_T$. A
   multiplicative lift is the natural shape for a revenue KPI: it leaves
   non-payers at zero and scales paying-user spend by 5%.
3. Run the methodology of Sections 3.2, 4, 6, and 7.1 exactly as written
   — group means and SEs from (1)-(3), absolute uplift from (4)-(5),
   relative uplift from (6), delta-method SE from (7)-(9), normal-normal
   conjugate update from (13)-(16), Pearson SRM check from (17).
4. Record $\hat\rho_t$, $\hat\sigma_{\text{obs},t}$, the posterior
   $\mu_{\text{post},t}, \sigma_{\text{post},t}$, the chance to beat
   control $P(\rho_t > 0 \,|\, \text{data})$, and the 95% credible
   interval.

We adopt a *skeptical* prior $\rho_t \sim \mathcal{N}(0, 0.05^2)$ — i.e.
$\mu_0 = 0$, $\sigma_0 = 0.05$, $\tau_0 = 400$ — so that the simulation
honestly measures how much of the recovered signal comes from data
rather than from a prior that already believes in the effect. (Section 9
discusses why fixed informed priors centered near the expected lift can
flatter the methodology.) The iteration is repeated $R = 100$ times with
independent random splits.

### 8.3 A single iteration, traced through the equations

We first walk one iteration (random seed $7$) in full so that every
number is anchored to a formula. The numbers below were produced by the
analysis script and are reproduced verbatim, rounded for readability.

**Sample-ratio mismatch check (Section 7.1, equation (17)).** By
construction $n_C = n_T = 97{,}762$ with intended split
$p_C = p_T = 1/2$, so $n p_g = 97{,}762$ and

$$
X^2 \;=\; \sum_{g} \frac{(n_g - n p_g)^2}{n p_g} \;=\; 0 ,
\qquad p\text{-value} \;=\; 1.0 .
$$

The SRM check passes trivially because the splitter is exact; in a real
experiment the corresponding $X^2$ would be small but nonzero.

**Group means and standard errors (equations (1)-(3)).**

| Group | $n_g$ | $\bar Y_g$ (USD) | $s_g$ (USD) | $\widehat{\mathrm{SE}}(\bar Y_g)$ (USD) |
|---|---|---|---|---|
| $C$ (control) | $97{,}762$ | $1.27916$ | $11.3812$ | $0.03640$ |
| $T$ (treatment, after $\times 1.05$) | $97{,}762$ | $1.37339$ | $12.0531$ | $0.03855$ |

For example, $\widehat{\mathrm{SE}}(\bar Y_C) = 11.3812 / \sqrt{97{,}762} \approx 0.03640$ from (3).
In particular $\bar Y_C^{\text{raw}} = 1.27916$ — this value is fixed as
the denominator of the relative-uplift estimator throughout this
iteration, as required by Section 4.2.

**Absolute uplift and its SE (equations (4)-(5)).**

$$
\hat\Delta_t \;=\; 1.37339 - 1.27916 \;=\; 0.09423 ,
$$

$$
\widehat{\mathrm{SE}}(\hat\Delta_t)
\;=\; \sqrt{0.03640^2 + 0.03855^2}
\;\approx\; 0.05302 .
$$

**Relative uplift (equation (6)).**

$$
\hat\rho_t \;=\; \frac{\hat\Delta_t}{\bar Y_C^{\text{raw}}}
\;=\; \frac{0.09423}{1.27916}
\;\approx\; 0.07367 \;(7.37\%) .
$$

This single sample overshoots the injected truth of $5.0\%$ by about two
percentage points; that is consistent with the SE we are about to
compute, not evidence of a problem with the estimator.

**Delta method (equations (7)-(9)).** The two partial-derivative
coefficients are

$$
\frac{1}{\bar Y_C^{\text{raw}}} \;=\; \frac{1}{1.27916} \;\approx\; 0.7818 ,
\qquad
\frac{\hat\Delta_t}{(\bar Y_C^{\text{raw}})^2}
\;=\; \frac{0.09423}{1.27916^2}
\;\approx\; 0.05759 ,
$$

so

$$
\widehat{\mathrm{Var}}(\hat\rho_t)
\;\approx\; (0.7818)^2 (0.05302)^2 + (0.05759)^2 (0.03640)^2
\;\approx\; 1.719{\times}10^{-3} + 4.39{\times}10^{-6}
\;\approx\; 1.723{\times}10^{-3} ,
$$

$$
\hat\sigma_{\text{obs},t}
\;=\; \sqrt{\widehat{\mathrm{Var}}(\hat\rho_t)}
\;\approx\; 0.04150 \;(4.15\%) .
$$

As predicted by the discussion after (8), the second term (denominator
sensitivity) contributes about $0.25\%$ of the total variance: virtually
all uncertainty in $\hat\rho_t$ comes from $\hat\Delta_t$.

**Bayesian update (equations (13)-(16)).** With the skeptical prior
$\rho_t \sim \mathcal{N}(0, 0.05^2)$,
$\tau_0 = 1/0.05^2 = 400$ and
$\tau_{\text{data},t} = 1/0.04150^2 \approx 580.7$, so

$$
\tau_{\text{post},t} \;=\; 400 + 580.7 \;=\; 980.7 ,
\qquad
\sigma_{\text{post},t} \;=\; \tau_{\text{post},t}^{-1/2}
\;\approx\; 0.03193 ,
$$

$$
\mu_{\text{post},t}
\;=\; \frac{400 \cdot 0 + 580.7 \cdot 0.07367}{980.7}
\;\approx\; 0.04362 \;(4.36\%) .
$$

Even though $\hat\rho_t$ overshot to $7.37\%$, the prior pulls the
posterior mean back toward $0$, landing at $4.36\%$ — strikingly close
to the injected truth of $5.0\%$. The 95% credible interval is

$$
0.04362 \pm 1.96 \cdot 0.03193 \;\approx\; [-0.019,\ 0.106] ,
$$

i.e. $[-1.9\%,\ +10.6\%]$, and

$$
P(\rho_t > 0 \,|\, \text{data})
\;=\; \Phi\!\bigl(0.04362 / 0.03193\bigr)
\;=\; \Phi(1.366)
\;\approx\; 0.914 .
$$

**Decision for this single iteration.** Under the $P(\rho_t > 0 \,|\, \text{data}) > 0.95$ rule from Section 6.3,
this single run does *not* declare a win — even though the true uplift
is positive, the data plus the skeptical prior do not clear the bar.
This is exactly the kind of trade-off the next subsection quantifies
across $R = 100$ such runs.

### 8.4 Aggregate results across $R = 100$ iterations

Repeating the protocol of Section 8.2 with fresh random splits gives a
distribution of estimates. Figure 3 plots two views: the histogram of
the relative-uplift estimator $\hat\rho_t$ across runs (left), and the
posterior means with 95% credible intervals for every run sorted by
posterior mean (right). The red dashed line marks the injected truth
$\rho^{\star} = 5\%$.

![Distribution of $\hat\rho_t$ and posterior credible intervals across $R = 100$ Monte-Carlo runs.](figures/fig3_simulation.png){ width=100% }

The table below summarizes the simulation.

| Quantity | Value across $R = 100$ runs |
|---|---|
| Injected true uplift $\rho^{\star}$ | $5.00\%$ |
| Mean of $\hat\rho_t$ | $4.69\%$ |
| Empirical SD of $\hat\rho_t$ across runs | $4.10\%$ |
| Mean delta-method $\hat\sigma_{\text{obs},t}$ | $4.10\%$ |
| Median $\hat\rho_t$ | $3.80\%$ |
| 2.5%, 97.5% percentiles of $\hat\rho_t$ | $-2.27\%,\ +12.75\%$ |
| Mean posterior mean $\mu_{\text{post},t}$ | $2.76\%$ |
| Mean posterior SD $\sigma_{\text{post},t}$ | $3.17\%$ |
| Mean $P(\rho_t > 0 \,|\, \text{data})$ | $0.756$ |
| Median $P(\rho_t > 0 \,|\, \text{data})$ | $0.765$ |
| Frequentist 95% CI coverage of $\rho^{\star}$ | $97\%$ |
| Bayesian 95% credible interval coverage of $\rho^{\star}$ | $96\%$ |
| Detection rate (Bayesian, $P > 0.95$) | $18\%$ |
| Detection rate (frequentist, 95% CI excludes $0$) | $23\%$ |

Two facts stand out.

**The pipeline is calibrated.** The empirical SD of $\hat\rho_t$ across
runs is $4.10\%$, and the delta-method estimate $\hat\sigma_{\text{obs},t}$
averages $4.10\%$ — agreement to three significant figures, with no
hand-tuning. The mean of $\hat\rho_t$ is $4.69\%$, within one twentieth
of the true $5.00\%$. The 95% credible interval contains the truth in
$96$ of $100$ runs, and the 95% frequentist confidence interval in $97$
of $100$ — both consistent with the nominal $95\%$ rate at this sample
size. In other words, when the methodology says "I think the lift is
roughly here, with this uncertainty," it is telling the truth.

**Power is the binding constraint for this KPI at one week.** Even
though $\hat\rho_t$ is unbiased and well-calibrated, a single run only
clears the $P > 0.95$ decision threshold $18\%$ of the time. The reason
is visible in the table above: $\hat\sigma_{\text{obs},t} \approx 4.1\%$
is comparable to the true effect $5\%$, so the Bayesian z-statistic
$\hat\rho_t / \hat\sigma_{\text{obs},t}$ has roughly unit mean and unit
spread and only crosses the equivalent of $z \approx 1.96$ on a minority
of runs. The Lorenz curve in Figure 2 is the proximate cause: a tiny
number of high-spending users dominate $s_g$, inflating
$\widehat{\mathrm{SE}}(\bar Y_g)$ and therefore
$\hat\sigma_{\text{obs},t}$.

### 8.5 What the simulation tells us

Every quantity reported above is traceable to the symbols introduced in
Section 2: $\bar Y_g$ to (1), $\widehat{\mathrm{SE}}(\bar Y_g)$ to (3),
$\hat\Delta_t$ to (4), $\hat\rho_t$ to (6),
$\hat\sigma_{\text{obs},t}$ to (8)-(9), the posterior summaries to
(14)-(16), and the SRM check to (17). The same symbols carry the same
meaning whether the inputs are invented or, as here, drawn from one week
of real IAP revenue.

For practice the simulation contains three actionable signals:

1. **The estimators are honest.** Delta-method SEs reproduce the actual
   sampling variability of $\hat\rho_t$, and 95% intervals cover the
   truth $\sim 95\%$ of the time. Reported uncertainty is not optimistic.
2. **Power on raw weekly IAP is limited.** With $\sim 98{,}000$ users
   per arm and one week of data, recovering a $5\%$ uplift at the
   $P > 0.95$ bar succeeds roughly $1$ time in $5$. Longer test windows,
   larger arms, or — most importantly — **CUPED variance reduction
   using pre-period spend** (Section 5) would shrink
   $\hat\sigma_{\text{obs},t}$ and lift the detection rate dramatically;
   the CUPED step is currently bypassed only because this particular
   dataset ships without a pre-period covariate vector.
3. **The prior choice matters.** A skeptical prior $\mathcal{N}(0, 0.05^2)$
   shrinks $\hat\rho_t$ toward zero and produces the $18\%$ detection
   rate above. An informed prior centered near $5\%$ — the
   $\mu_0 = 0.05$ choice of v2 — would have made the posterior mean
   land essentially on $5\%$ regardless of the data and pushed the
   detection rate much higher, but at the cost of measuring the prior
   rather than the data. The discussion in Section 9 of "rigid informed
   priors" applies directly here."""

new_src = src[:i] + NEW_SECTION_8 + "\n\n" + src[j:]
V3.write_text(new_src)
print("v3 length lines:", new_src.count("\n") + 1)
